apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  # kv format
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  PG_DATA: /var/lib/postgresql/data/pgdata

  USER_DB_SERVICE: user-db
  NOTIFICATION_DB_SERVICE: notification-db
  POST_DB_SERVICE: post-db
